{
  "openapi": "3.0.2",
  "info": {
    "title": "Cuanmax RESTful API",
    "version": "1.1.2",
    "description": "RESTful API for Cuanmax Application",
    "contact": {
      "name": "Iwan Suryaningrat",
      "email": "iwansuryaningrat@cuanmax.id"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Cuanmax RESTful API Server for Production",
      "url": "https://cuanmax-api.tech/v1"
    },
    {
      "description": "Cuanmax RESTful API Server for Development",
      "url": "http://localhost:8080/v1"
    }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Signup",
        "description": "Signup to Cuanmax",
        "operationId": "signup",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Name of user",
                    "example": "Name User"
                  },
                  "username": {
                    "type": "string",
                    "description": "Username of user",
                    "example": "username"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "description": "Email of user",
                    "example": "example@mail.com"
                  },
                  "password": {
                    "type": "string",
                    "format": "password"
                  },
                  "admin": {
                    "type": "boolean",
                    "description": "Is admin or not",
                    "example": false,
                    "default": false,
                    "nullable": true
                  }
                },
                "required": ["name", "email", "password"],
                "example": {
                  "name": "User Name",
                  "username": "username",
                  "email": "email@example.com",
                  "password": "password",
                  "admin": false
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User registered successfully! Please check your email."
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Name, username, email and password are required."
                  }
                }
              }
            }
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/auth/verifyAccount/{token}": {
      "put": {
        "tags": ["Authentication"],
        "summary": "Verify Account",
        "description": "Verify Account to Cuanmax",
        "operationId": "verifyAccount",
        "parameters": [
          {
            "$ref": "#/components/parameters/token"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User was verified successfully!",
                    "email": "example@mail.com"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Token is required."
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Login",
        "description": "Login to Cuanmax",
        "operationId": "login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "password": {
                    "type": "string",
                    "format": "password"
                  },
                  "rememberMe": {
                    "type": "boolean",
                    "description": "Remember me or not",
                    "example": false,
                    "default": false,
                    "nullable": true
                  }
                },
                "required": ["email", "password"],
                "example": {
                  "email": "example@mail.com",
                  "password": "123456",
                  "rememberMe": false
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Login Success!",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTI4MzgxNzk5NjExY2NjNzQ4ZmI4YyIsImVtYWlsIjoiaXdhbi5zdXJ5YW5pbmdyYXRAc3R1ZGVudHMudW5kaXAuYWMuaWQiLCJuYW1lIjoiSXdhbiIsImFkbWluIjpmYWxzZSwicm9sZSI6IiBCYXNpYyBNZW1iZXIiLCJpYXQiOjE2NTQ0NDQ0MDIsImV4cCI6MTY1NDQ0ODAwMn0.s5nfB81F6X5E8wBD0DIRqmP5NNuCQFpGllXEMPfbyeY"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Invalid Email or Password!"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/auth/resetPassword": {
      "put": {
        "tags": ["Authentication"],
        "summary": "Reset Password",
        "description": "Reset Password",
        "operationId": "resetPassword",
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "description": "JWT Token",
            "required": true,
            "allowEmptyValue": false,
            "schema": {
              "type": "string",
              "format": "int64"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  },
                  "oldPassword": {
                    "type": "string",
                    "format": "password"
                  },
                  "newPassword": {
                    "type": "string",
                    "format": "password"
                  }
                },
                "required": ["email", "oldPassword", "newPassword"],
                "example": {
                  "email": "example@mail.com",
                  "oldPassword": "123456",
                  "newPassword": "new123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "token": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Password has been changed!",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNmJmZWFhMDFmNmMyYWViNjhhYjJlOCIsImVtYWlsIjoiaXdhbmFkbWluQGdtYWlsLmNvbSIsIm5hbWUiOiJJd2FuIFN1cnlhbmluZ3JhdCIsImFkbWluIjp0cnVlLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2NjgwMjQyODgsImV4cCI6MTY2ODA2NzQ4OH0.v_d_qp_FHYI_LA2njNyETKxN6xfuLuK4GuH9kDIE6-o"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Old Password and New Password can't be empty!"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/auth/forgotPassword": {
      "post": {
        "tags": ["Authentication"],
        "summary": "Forgot Password",
        "description": "Forgot Password",
        "operationId": "forgotPassword",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                },
                "required": ["email"],
                "example": {
                  "email": "example@mail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Email has been sent!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Email can't be empty!"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/auth/resetPassword/{token}": {
      "put": {
        "tags": ["Authentication"],
        "summary": "Reset Password with Token",
        "description": "Reset Password with Token",
        "operationId": "resetPasswordwithToken",
        "parameters": [
          {
            "$ref": "#/components/parameters/token"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string",
                    "format": "password"
                  }
                },
                "required": ["password"],
                "example": {
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Password has been changed, please login!"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Password can't be empty!"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/messages": {
      "post": {
        "tags": ["Messages"],
        "summary": "Send Messages",
        "description": "Send Messages",
        "operationId": "sendMessages",
        "requestBody": {
          "description": "Send Messages",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "latstName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "subject": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  }
                },
                "example": {
                  "firstName": "John",
                  "lastName": "Doe",
                  "email": "example@mail.com",
                  "subject": "Lorem ipsum dolor sit amet",
                  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "subject",
                  "body"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully sent."
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/messages": {
      "get": {
        "tags": ["Messages - Admin"],
        "summary": "Get All Messages",
        "description": "Get All Messages",
        "operationId": "getAllMessages",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "firstName": {
                            "type": "string"
                          },
                          "lastName": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "subject": {
                            "type": "string"
                          },
                          "message": {
                            "type": "string"
                          },
                          "status": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully fetched.",
                  "data": [
                    {
                      "id": "5f9c1b9b9c9c1c0017b5b1b1",
                      "firstName": "John",
                      "lastName": "Doe",
                      "email": "example@mail.com",
                      "subject": "Lorem ipsum dolor sit amet",
                      "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                      "status": "unread"
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/messages/{Message ID}": {
      "get": {
        "tags": ["Messages - Admin"],
        "summary": "Get Messages By ID",
        "description": "Get Messages By ID",
        "operationId": "getMessagesByID",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/Message ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "firstName": {
                          "type": "string"
                        },
                        "lastName": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "subject": {
                          "type": "string"
                        },
                        "message": {
                          "type": "string"
                        },
                        "status": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully fetched.",
                  "data": {
                    "id": "5f9c1b9b9c9c1c0017b5b1b1",
                    "firstName": "John",
                    "lastName": "Doe",
                    "email": "example@mail.com",
                    "subject": "Lorem ipsum dolor sit amet",
                    "message": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
                    "status": "unread"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": ["Messages - Admin"],
        "summary": "Delete Messages By ID",
        "description": "Delete Messages By ID",
        "operationId": "deleteMessagesByID",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/Message ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully deleted."
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/messages/{Message ID}/read": {
      "put": {
        "tags": ["Messages - Admin"],
        "summary": "Read Messages By ID",
        "description": "Read Messages By ID",
        "operationId": "readMessagesByID",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/Message ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully read."
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/messages/{Message ID}/reply": {
      "post": {
        "tags": ["Messages - Admin"],
        "summary": "Reply Messages By ID",
        "description": "Reply Messages By ID",
        "operationId": "replyMessagesByID",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/Message ID"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "reply": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "reply": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Messages successfully replied."
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "x-auth-token": {
        "name": "x-auth-token",
        "in": "header",
        "description": "JWT Token",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string",
          "format": "int64"
        }
      },
      "token": {
        "name": "token",
        "in": "path",
        "description": "Token",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "Liveclass ID": {
        "name": "Liveclass ID",
        "in": "path",
        "description": "Liveclass ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Liveclass Transaction ID": {
        "name": "Liveclass Transaction ID",
        "in": "path",
        "description": "Liveclass Transaction ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Membership Transaction ID": {
        "name": "Membership Transaction ID",
        "in": "path",
        "description": "Membership Transaction ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Message ID": {
        "name": "Message ID",
        "in": "path",
        "description": "Message ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "News ID": {
        "name": "News ID",
        "in": "path",
        "description": "News ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Playlist ID": {
        "name": "Playlist ID",
        "in": "path",
        "description": "Playlist ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Plans ID": {
        "name": "Plans ID",
        "in": "path",
        "description": "Plans ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Service ID": {
        "name": "Service ID",
        "in": "path",
        "description": "ID of the service",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        },
        "example": "5f9f1b9b9c9d2b0017a5b0b1"
      },
      "Subscriber ID": {
        "name": "Subscriber ID",
        "in": "path",
        "description": "Subscriber ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Team ID": {
        "name": "Team ID",
        "in": "path",
        "description": "Team ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Testimoni ID": {
        "name": "Testimoni ID",
        "in": "path",
        "description": "Testimoni ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "User ID": {
        "name": "User ID",
        "in": "path",
        "description": "User ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Video ID": {
        "name": "Video ID",
        "in": "path",
        "description": "Video ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Voucher ID": {
        "name": "VOucher ID",
        "in": "path",
        "description": "VOucher ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      },
      "Watchlist ID": {
        "name": "Watchlist ID",
        "in": "path",
        "description": "Watchlist ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "responses": {
      "Bad Request": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User ID is Required!"
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "No token, authorization denied!"
              }
            }
          }
        }
      },
      "Forbidden": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "You are not authorized to do this action!"
              }
            }
          }
        }
      },
      "Not Found": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User not found!"
              }
            }
          }
        }
      },
      "Method Not Allowed": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Method Not Allowed!"
              }
            }
          }
        }
      },
      "Conflict": {
        "description": "Conflict",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User Already Exist. Please Login"
              }
            }
          }
        }
      },
      "Unprocessable Entity": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "No file uploaded"
              }
            }
          }
        }
      },
      "Internal Server Error": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Some error occurred while fetching data!"
              }
            }
          }
        }
      },
      "Show Profile Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "address": {
                      "type": "string"
                    },
                    "birthday": {
                      "type": "string"
                    },
                    "image": {
                      "type": "string"
                    },
                    "type": {
                      "type": "object",
                      "properties": {
                        "memberType": {
                          "type": "string"
                        },
                        "subscription": {
                          "type": "object",
                          "properties": {
                            "startAt": {
                              "type": "number"
                            },
                            "expiredAt": {
                              "type": "number"
                            }
                          }
                        },
                        "isNew": {
                          "type": "boolean"
                        },
                        "isAdmin": {
                          "type": "boolean"
                        },
                        "isActivated": {
                          "type": "boolean"
                        }
                      }
                    },
                    "referral": {
                      "type": "object",
                      "properties": {
                        "referralCode": {
                          "type": "string"
                        },
                        "referralCount": {
                          "type": "number"
                        },
                        "referralAccount": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "username": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "message": "User fetched successfully!",
                "data": {
                  "name": "Example Name",
                  "username": "username",
                  "email": "example@mail.com",
                  "image": "https://res.cloudinary.com/dzqbzqgjw/image/upload/v1599098981/default-user-image_qjqjqj.png",
                  "phone": "081234567890",
                  "address": "Jl. Example",
                  "birthday": "1990-01-01",
                  "type": {
                    "memberType": "Pro Member",
                    "subscription": {
                      "startat": "Tue Nov 15 2022 01:59:28 GMT+0700 (Western Indonesia Time)",
                      "expiredAt": null
                    },
                    "isNew": true,
                    "isAdmin": false,
                    "isActivated": false
                  },
                  "referral": {
                    "referralCode": "123456",
                    "referralCount": 0,
                    "referralAccount": []
                  }
                }
              }
            }
          }
        }
      },
      "Update Profile Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              }
            },
            "example": {
              "message": "User updated successfully!",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
            }
          }
        }
      },
      "Change Password Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Password changed successfully!"
              }
            }
          }
        }
      },
      "Change Profile Picture Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              }
            },
            "example": {
              "message": "Picture changed successfully!",
              "token": "5f9c1b9b9c9c1c0017b5b1b1"
            }
          }
        }
      }
    },
    "requestBodies": {
      "Edit Profile": {
        "description": "Edit Profile",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "address": {
                  "type": "string"
                },
                "birthday": {
                  "type": "string"
                }
              },
              "required": ["name", "phone", "address", "birthday"],
              "example": {
                "name": "Example Name",
                "phone": "081234567890",
                "address": "Example Address",
                "birthday": "1990-01-01"
              }
            }
          }
        }
      },
      "Change Password": {
        "description": "Change Password",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "oldPassword": {
                  "type": "string"
                },
                "newPassword": {
                  "type": "string"
                }
              },
              "required": ["oldPassword", "newPassword"],
              "example": {
                "oldPassword": "123456",
                "newPassword": "1234567"
              }
            }
          }
        }
      },
      "Change Profile Picture": {
        "description": "Change Profile Picture",
        "content": {
          "multipart/form-data": {
            "schema": {
              "type": "object",
              "properties": {
                "image": {
                  "type": "string",
                  "format": "binary",
                  "required": true,
                  "description": "Image file",
                  "nullable": false
                }
              }
            },
            "example": {
              "image": "file"
            }
          }
        }
      },
      "Teams Body": {
        "description": "Teams Body",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "position": {
                  "type": "string"
                },
                "instagram": {
                  "type": "string"
                },
                "email": {
                  "type": "string"
                },
                "twitter": {
                  "type": "string"
                },
                "linkedin": {
                  "type": "string"
                }
              },
              "example": {
                "name": "Name",
                "description": "description",
                "position": "CEO",
                "instagram": "https://www.instagram.com/username/",
                "email": "example@mail.com",
                "twitter": "https://www.twitter.com/username/",
                "linkedin": "https://www.linkedin.com/username/"
              },
              "required": ["name", "description", "position"]
            }
          }
        }
      },
      "Testimoni Body": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "position": {
                  "type": "string"
                },
                "company": {
                  "type": "string"
                },
                "testimoni": {
                  "type": "string"
                }
              },
              "required": ["name", "position", "company", "testimoni"],
              "example": {
                "name": "John Doe",
                "position": "CEO",
                "company": "PT. Example",
                "testimoni": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
              }
            }
          }
        }
      }
    }
  }
}
