{
  "openapi": "3.0.2",
  "info": {
    "title": "Cuanmax RESTful API",
    "version": "1.0.0",
    "description": "RESTful API for Cuanmax Application",
    "contact": {
      "name": "Iwan Suryaningrat",
      "email": "iwansuryaningrat@cuanmax.id"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Cuanmax RESTful API Server",
      "url": "http://159.223.84.116/api/v1"
    }
  ],
  "paths": {
    "/admin/users/": {
      "get": {
        "tags": ["Users - Admin"],
        "summary": "Get All Users",
        "description": "Get All Users for Admin",
        "operationId": "getUsers",
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "description": "JWT Token",
            "required": true,
            "allowEmptyValue": false,
            "schema": {
              "type": "string",
              "format": "int64"
            }
          },
          {
            "name": "admin",
            "in": "query",
            "description": "Parameter for Admin Filter",
            "required": false,
            "allowEmptyValue": true,
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "basic",
            "in": "query",
            "description": "Parameter for Basic Member Filter",
            "required": false,
            "allowEmptyValue": true,
            "schema": {
              "type": "boolean"
            }
          },
          {
            "name": "pro",
            "in": "query",
            "description": "Parameter for Pro Member Filter",
            "required": false,
            "allowEmptyValue": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "username": {
                            "type": "string"
                          },
                          "email": {
                            "type": "string"
                          },
                          "phone": {
                            "type": "string"
                          },
                          "address": {
                            "type": "string"
                          },
                          "birthday": {
                            "type": "string"
                          },
                          "memberType": {
                            "type": "string"
                          },
                          "subscription": {
                            "type": "object",
                            "properties": {
                              "startAt": {
                                "type": "number"
                              },
                              "expiredAt": {
                                "type": "number"
                              }
                            }
                          },
                          "isNew": {
                            "type": "boolean"
                          },
                          "adminType": {
                            "type": "string"
                          },
                          "isActivated": {
                            "type": "boolean"
                          }
                        }
                      }
                    }
                  },
                  "example": {
                    "message": "Users fetched successfully!",
                    "data": [
                      {
                        "id": "5f9f1b9b9b9b9b9b9b9b9b9b",
                        "name": "Admin",
                        "username": "admin",
                        "email": "example@mail.com",
                        "phone": "081234567890",
                        "address": "Jl. Jalan",
                        "birthday": "1999-01-01",
                        "memberType": "Admin",
                        "subscription": {
                          "startat": "Tue Nov 15 2022 01:59:28 GMT+0700 (Western Indonesia Time)",
                          "expiredAt": "Tue Nov 15 2022 01:59:28 GMT+0700 (Western Indonesia Time)"
                        },
                        "isNew": false,
                        "adminType": "Super Admin",
                        "isActivated": true
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/users/{User ID}": {
      "get": {
        "tags": ["Users - Admin"],
        "summary": "Get User by ID",
        "description": "Get User by ID for Admin",
        "operationId": "getUserAdmin",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/Show Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      },
      "delete": {
        "tags": ["Users - Admin"],
        "summary": "Delete User by ID",
        "description": "Delete User by ID for Admin",
        "operationId": "deleteUserAdmin",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "User deleted successfully!"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "405": {
            "$ref": "#/components/responses/Method Not Allowed"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      },
      "put": {
        "tags": ["Users - Admin"],
        "summary": "Update User by ID",
        "description": "Update User by ID for Admin",
        "operationId": "updateUserAdmin",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Edit Profile"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Update Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/users/{User ID}/changepassword": {
      "put": {
        "tags": ["Users - Admin"],
        "summary": "Change Password by ID",
        "description": "Change Password by ID for Admin",
        "operationId": "changePasswordAdmin",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Password"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Password Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/admin/users/{User ID}/changepicture": {
      "put": {
        "tags": ["Users - Admin"],
        "summary": "Change Picture by ID",
        "description": "Change Picture by ID for Admin",
        "operationId": "changePictureAdmin",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Profile Picture"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Profile Picture Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "422": {
            "$ref": "#/components/responses/Unprocessable Entity"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/pro/users/{User ID}": {
      "get": {
        "tags": ["Users - Pro Member"],
        "summary": "Get User by ID",
        "description": "Get User by ID for Pro Member",
        "operationId": "getUserPro",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/Show Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      },
      "put": {
        "tags": ["Users - Pro Member"],
        "summary": "Update User by ID",
        "description": "Update User by ID for Pro Member",
        "operationId": "updateUserProMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Edit Profile"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Update Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/pro/users/{User ID}/changepassword": {
      "put": {
        "tags": ["Users - Pro Member"],
        "summary": "Change Password by ID",
        "description": "Change Password by ID for Pro Member",
        "operationId": "changePasswordProMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Password"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Password Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/pro/users/{User ID}/changepicture": {
      "put": {
        "tags": ["Users - Pro Member"],
        "summary": "Change Picture by ID",
        "description": "Change Picture by ID for Pro Member",
        "operationId": "changePictureProMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Profile Picture"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Profile Picture Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "422": {
            "$ref": "#/components/responses/Unprocessable Entity"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/pro/users/{User ID}/createreferralcode": {
      "put": {
        "tags": ["Users - Pro Member"],
        "summary": "Create Referral Code by ID",
        "description": "Create Referral Code by ID for Pro Member",
        "operationId": "createReferralCodeProMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "referralCode": {
                    "type": "string",
                    "description": "Referral Code with max 8 characters",
                    "nullable": true,
                    "maxLength": 8
                  }
                }
              },
              "example": {
                "referralCode": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "referral": {
                          "type": "object",
                          "properties": {
                            "referralCode": {
                              "type": "string"
                            },
                            "referralCount": {
                              "type": "integer"
                            },
                            "referralAccount": {
                              "type": "array",
                              "items": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "message": "Referral code created successfully!",
                  "data": {
                    "referral": {
                      "referralCode": "123456",
                      "referralCount": 0,
                      "referralAccount": []
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/users/{User ID}": {
      "get": {
        "tags": ["Users - Basic Member"],
        "summary": "Get User by ID",
        "description": "Get User by ID for Basic Member",
        "operationId": "getUserBasic",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/Show Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      },
      "put": {
        "tags": ["Users - Basic Member"],
        "summary": "Update User by ID",
        "description": "Update User by ID for Basic Member",
        "operationId": "updateUserBasicMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Edit Profile"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Update Profile Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/users/{User ID}/changepassword": {
      "put": {
        "tags": ["Users - Basic Member"],
        "summary": "Change Password by ID",
        "description": "Change Password by ID for Basic Member",
        "operationId": "changePasswordBasicMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Password"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Password Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/users/{User ID}/changepicture": {
      "put": {
        "tags": ["Users - Basic Member"],
        "summary": "Change Picture by ID",
        "description": "Change Picture by ID for Basic Member",
        "operationId": "changePictureBasicMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/Change Profile Picture"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/Change Profile Picture Success"
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "422": {
            "$ref": "#/components/responses/Unprocessable Entity"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    },
    "/users/{User ID}/requestuseractivation": {
      "post": {
        "tags": ["Users - Basic Member"],
        "summary": "Request User Activation by ID",
        "description": "Request User Activation by ID for Basic Member",
        "operationId": "requestUserActivationBasicMember",
        "parameters": [
          {
            "$ref": "#/components/parameters/x-auth-token"
          },
          {
            "$ref": "#/components/parameters/User ID"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Activation email sent"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/Bad Request"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "404": {
            "$ref": "#/components/responses/Not Found"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          },
          "500": {
            "$ref": "#/components/responses/Internal Server Error"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "x-auth-token": {
        "name": "x-auth-token",
        "in": "header",
        "description": "JWT Token",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string",
          "format": "int64"
        }
      },
      "token": {
        "name": "token",
        "in": "path",
        "description": "Token",
        "required": true,
        "schema": {
          "type": "string"
        }
      },
      "User ID": {
        "name": "User ID",
        "in": "path",
        "description": "User ID",
        "required": true,
        "allowEmptyValue": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "responses": {
      "Bad Request": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User ID is Required!"
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "Unauthorized",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "No token, authorization denied!"
              }
            }
          }
        }
      },
      "Forbidden": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "You are not authorized to do this action!"
              }
            }
          }
        }
      },
      "Not Found": {
        "description": "Not Found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User not found!"
              }
            }
          }
        }
      },
      "Method Not Allowed": {
        "description": "Method Not Allowed",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Method Not Allowed!"
              }
            }
          }
        }
      },
      "Conflict": {
        "description": "Conflict",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "User Already Exist. Please Login"
              }
            }
          }
        }
      },
      "Unprocessable Entity": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "No file uploaded"
              }
            }
          }
        }
      },
      "Internal Server Error": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Some error occurred while fetching data!"
              }
            }
          }
        }
      },
      "Show Profile Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "data": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "username": {
                      "type": "string"
                    },
                    "email": {
                      "type": "string"
                    },
                    "phone": {
                      "type": "string"
                    },
                    "address": {
                      "type": "string"
                    },
                    "birthday": {
                      "type": "string"
                    },
                    "image": {
                      "type": "string"
                    },
                    "type": {
                      "type": "object",
                      "properties": {
                        "memberType": {
                          "type": "string"
                        },
                        "subscription": {
                          "type": "object",
                          "properties": {
                            "startAt": {
                              "type": "number"
                            },
                            "expiredAt": {
                              "type": "number"
                            }
                          }
                        },
                        "isNew": {
                          "type": "boolean"
                        },
                        "isAdmin": {
                          "type": "boolean"
                        },
                        "isActivated": {
                          "type": "boolean"
                        }
                      }
                    },
                    "referral": {
                      "type": "object",
                      "properties": {
                        "referralCode": {
                          "type": "string"
                        },
                        "referralCount": {
                          "type": "number"
                        },
                        "referralAccount": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "username": {
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "example": {
                "message": "User fetched successfully!",
                "data": {
                  "name": "Example Name",
                  "username": "username",
                  "email": "example@mail.com",
                  "image": "https://res.cloudinary.com/dzqbzqgjw/image/upload/v1599098981/default-user-image_qjqjqj.png",
                  "phone": "081234567890",
                  "address": "Jl. Example",
                  "birthday": "1990-01-01",
                  "type": {
                    "memberType": "Pro Member",
                    "subscription": {
                      "startat": "Tue Nov 15 2022 01:59:28 GMT+0700 (Western Indonesia Time)",
                      "expiredAt": null
                    },
                    "isNew": true,
                    "isAdmin": false,
                    "isActivated": false
                  },
                  "referral": {
                    "referralCode": "123456",
                    "referralCount": 0,
                    "referralAccount": []
                  }
                }
              }
            }
          }
        }
      },
      "Update Profile Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              }
            },
            "example": {
              "message": "User updated successfully!",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
            }
          }
        }
      },
      "Change Password Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                }
              },
              "example": {
                "message": "Password changed successfully!"
              }
            }
          }
        }
      },
      "Change Profile Picture Success": {
        "description": "Successful Operation",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string"
                },
                "token": {
                  "type": "string"
                }
              }
            },
            "example": {
              "message": "Picture changed successfully!",
              "token": "5f9c1b9b9c9c1c0017b5b1b1"
            }
          }
        }
      }
    },
    "requestBodies": {
      "Edit Profile": {
        "description": "Edit Profile",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "phone": {
                  "type": "string"
                },
                "address": {
                  "type": "string"
                },
                "birthday": {
                  "type": "string"
                }
              },
              "required": ["name", "phone", "address", "birthday"],
              "example": {
                "name": "Example Name",
                "phone": "081234567890",
                "address": "Example Address",
                "birthday": "1990-01-01"
              }
            }
          }
        }
      },
      "Change Password": {
        "description": "Change Password",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "oldPassword": {
                  "type": "string"
                },
                "newPassword": {
                  "type": "string"
                }
              },
              "required": ["oldPassword", "newPassword"],
              "example": {
                "oldPassword": "123456",
                "newPassword": "1234567"
              }
            }
          }
        }
      },
      "Change Profile Picture": {
        "description": "Change Profile Picture",
        "content": {
          "multipart/form-data": {
            "schema": {
              "type": "object",
              "properties": {
                "image": {
                  "type": "string",
                  "format": "binary",
                  "required": true,
                  "description": "Image file",
                  "nullable": false
                }
              }
            },
            "example": {
              "image": "file"
            }
          }
        }
      }
    }
  }
}
